# Start in nord-theme
run-shell "~/.tmux/themes/nord-tmux/nord.tmux"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Fix vim color issue
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set-window-option -g mode-keys vi

unbind -T copy-mode-vi Space; #Default for begin-selection
unbind -T copy-mode-vi Enter; #Default for copy-selection

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel --clipboard"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"`
