#!/bin/bash

# Prints out the number of pacman updates (Arch Linux)
# Requires an internet connection
# Depends on yay and checkupdates (pacman-contrib)
# Optional: add --devel flag to the yay cmd to check for *-git package updates.

PREFIX='󰌌'

get_updates()
{
    caps_lock_status=$(xset -q | sed -n 's/^.*Caps Lock:\s*\(\S*\).*$/\1/p')
    if [ $caps_lock_status == "on" ]; then
        LAYOUT=$(xkblayout-state print "%s" | tr a-z A-z)
    else
        LAYOUT=$(xkblayout-state print "%s")
    fi

    echo "$PREFIX $LAYOUT"
}

get_updates
